version 0.2-6

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -133,7 +133,7 @@ GDALAllRegister();
 #endif
 _EOCONF]
 
-AC_MSG_CHECKING(gdal: linking with --libs only)
+AC_MSG_CHECKING(GDAL: linking with --libs only)
 ${CXX} ${CPPFLAGS} -o gdal_test gdal_test.cpp ${LIBS} 2> errors.txt
 if test `echo $?` -ne 0 ; then
 gdalok=no
@@ -143,7 +143,7 @@ AC_MSG_RESULT(yes)
 fi
 
 if test "${gdalok}" = no; then
-AC_MSG_CHECKING(gdal: linking with --libs and --dep-libs)
+AC_MSG_CHECKING(GDAL: linking with --libs and --dep-libs)
 LIBS="${LIBS} ${GDAL_DEP_LIBS}"
 gdalok=yes
 ${CXX} ${CPPFLAGS} -o gdal_test gdal_test.cpp ${LIBS} 2>> errors.txt
@@ -214,8 +214,112 @@ AC_MSG_NOTICE([Copy data for:])
   fi
 fi
 
+#
+# test whether PROJ.4 is available to gdal:
+#
 
+gdal_has_proj=no
+[cat > gdal_proj.cpp <<_EOCONF
+#include <gdal.h>
+#include <ogr_srs_api.h>
+#include <ogr_spatialref.h>
+int main(int argc, char *argv[]) {
+	OGRSpatialReference *dest = new OGRSpatialReference;
+	OGRSpatialReference *src = new OGRSpatialReference;
+    src->importFromEPSG(4326);
+    dest->importFromEPSG(3857);
+	OGRCoordinateTransformation *ct = OGRCreateCoordinateTransformation(src, dest);
+	return(ct == NULL); // signals PROJ.4 is not available through gdal
+}
+_EOCONF]
+
+AC_MSG_CHECKING(GDAL: checking whether PROJ.4 is available for linking:)
+${CXX} ${CPPFLAGS} -o gdal_proj gdal_proj.cpp ${LIBS} 2> errors.txt
+if test `echo $?` -ne 0 ; then
+gdal_has_proj=no
+AC_MSG_RESULT(no)
+else
+gdal_has_proj=yes
+AC_MSG_RESULT(yes)
+fi
+
+if test "${gdal_has_proj}" = no; then
+   cat errors.txt
+   AC_MSG_NOTICE([Install failure: compilation and/or linkage problems.])
+   AC_MSG_ERROR([cannot link projection code])
+fi
+
+AC_MSG_CHECKING(GDAL: checking whether PROJ.4 is available fur running:)
+./gdal_proj
+if test `echo $?` -ne 0 ; then
+gdal_has_proj=no
+AC_MSG_RESULT(no)
+else
+gdal_has_proj=yes
+AC_MSG_RESULT(yes)
+fi
+if test "${gdal_has_proj}" = no; then
+   AC_MSG_ERROR([OGRCoordinateTransformation() does not return a coord.trans: PROJ.4 not available?])
+fi
+rm -fr errors.txt gdal_proj.cpp gdal_proj
+
+#
+# test whether gdal has GEOS support:
+#
+
+gdal_has_geos=no
+[cat > gdal_geos.cpp <<_EOCONF
+#include <gdal.h>
+#include <ogr_api.h>
+#include <ogr_geometry.h>
+int main(int argc, char *argv[]) {
+   const char* wkt1 = "POINT(0 0)";
+   char* pszWkt1 = (char*) wkt1;
+   OGRSpatialReferenceH ref = OSRNewSpatialReference(NULL);
+   OGRGeometryH new_geom1;
+   OGRErr err = OGR_G_CreateFromWkt(&pszWkt1, ref, &new_geom1);
+   const char* wkt2 = "POINT(1 1)";
+   char* pszWkt2 = (char*) wkt2;
+   OGRGeometryH new_geom2;
+   err = OGR_G_CreateFromWkt(&pszWkt2, ref, &new_geom2);
+   CPLPushErrorHandler(CPLQuietErrorHandler);
+   return OGR_G_Union(new_geom1, new_geom2) == NULL;
+}
+_EOCONF]
+
+AC_MSG_CHECKING(GDAL: checking geos support linking:)
+${CXX} ${CPPFLAGS} -o gdal_geos gdal_geos.cpp ${LIBS} 2> errors.txt
+if test `echo $?` -ne 0 ; then
+gdal_has_geos=no
+AC_MSG_RESULT(no)
+else
+gdal_has_geos=yes
+AC_MSG_RESULT(yes)
+fi
+
+#if test "${gdal_has_geos}" = no; then
+#   cat errors.txt
+#   AC_MSG_NOTICE([Install failure: compilation and/or linkage problems.])
+#   AC_MSG_ERROR([GDAL was configured without GEOS support: install GEOS first?])
+#fi
+
+AC_MSG_CHECKING(GDAL: checking geos support runtime:)
+./gdal_geos
+if test `echo $?` -ne 0 ; then
+gdal_has_geos=no
+AC_MSG_RESULT(no)
+else
+gdal_has_geos=yes
+AC_MSG_RESULT(yes)
+fi
+#if test "${gdal_has_geos}" = no; then
+#   AC_MSG_ERROR([Union() returns NULL: GDAL was configured without GEOS: install GEOS first?])
+#fi
+rm -fr errors.txt gdal_geos.cpp gdal_geos
+
+#
 # GEOS:
+#
 
 AC_MSG_CHECKING(geos-config usability)
 GEOS_CONFIG=`which geos-config`
